server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: demo-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/${spring.data.mongodb.database}}
      database: ${MONGODB_DATABASE:demo-17-cloud}
      auto-index-creation: true
      map-key-dot-replacement: "##"

api:
  common-service:
    url: ${COMMON_SERVICE_URL:http://localhost:8081}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  pattern:
    console: ${LOG_PATTERN:%d{yyyy-MM-dd HH:mm:ss} ${spring.application.name} %-5level - %logger - %msg%n}
